spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  redis:
    host: localhost
    port: 6300
  cache:
    redis:
      time-to-live: 60

logging:
  level:
    org:
      hibernate:
        type: trace